### ISSUE TITLE
Source code archive bug

### ISSUE THREAD

**Issue by killondark** [skryukov/skooma#23]
Hi @skryukov. In the last release of gem I has a bug:
Into `.../skooma/examples/rails_app` I run 
`bundle install && bundle exec rspec` but I see 
```
Failure/Error: config.include Skooma::RSpec[bar_openapi, path_prefix: "/bar", coverage: :strict], :bar_api

ArgumentError:
  unknown keyword: :coverage
```
I compare your "sorce code.zip" and file into github. Them is different. Please, checks and reupload source code.
Example for file `lib/skooma/matchers/wrapper.rb`:
```
# source code.zip
def initialize(helper_methods_module, openapi_path, base_uri: "https://skoomarb.dev/", path_prefix: "")

# github version
def initialize(helper_methods_module, openapi_path, base_uri: "https://skoomarb.dev/", path_prefix: "", **params)

**Comment by skryukov** [comment]
Hey, @killondark thanks for the issue!

The coverage feature wasn't available at the time, but I've just released a new version of the gem, `v0.3.1`. It should be all set now!
